version: '3.8'

services:
  demo-page2:
    container_name: demo_page2
    build: .
    ports:
      - "4001:4001"
    env_file:   
      - .env 
    networks:
      - pg_postgres-network
      - nginx-proxy-manager_default
    volumes:
      - demo_page2_data:/path/in/container

networks:
  pg_postgres-network:
    external: true
  nginx-proxy-manager_default:
    external: true

volumes:
  demo_page2_data:
    driver: local
